### ISSUE TITLE
`drugcmap2.xls` cannot be downloaded

### ISSUE THREAD

**Issue by Shicheng-Guo** [tgirke/longevityTools#3]
Dear Sir/Madam, 

I find this file `drugcmap2.xls` is not available now in this [page](http://girke.bioinformatics.ucr.edu/longevityTools/mydoc/mydoc_longevityTools_eDRUG_07.html#:~:text=The%20connectivity%20maps%20approach%20is,sorted%20(ranked)%20gene%20lists). 

The following uses the 1,497 age-related gene expression signatures from Peters et al. (2015) as a query against the CMAP signatures. The results are sorted by the ES Distance and the top scoring 20 drugs are given below. The full result table is
written to a file named drugcmap2.xls

http://biocluster.ucr.edu/~tgirke/projects/longevity/cmap/results/drugcmap2.xls

Can you help me to make a double-check? Thanks. 

Shicheng

**Comment by tgirke** [comment]
Please use this URL instead as the domain name has changed: http://cluster.hpcc.ucr.edu/~tgirke/projects/longevity/cmap/results/drugcmap2.xls
